# https://github.com/kentcdodds/kentcdodds.com/blob/main/.github/workflows/deployment.yml
name: CI
on:
  push:
    branches:
      - main
  pull_request: {}

env:
  NEXT_PUBLIC_SHOW_LOGGER: ${{ secrets.NEXT_PUBLIC_SHOW_LOGGER }}
  NEXT_PUBLIC_CHATWOOT_ID: ${{ secrets.NEXT_PUBLIC_CHATWOOT_ID }}
  NEXT_PUBLIC_COOKIEBOT_ID: ${{ secrets.NEXT_PUBLIC_COOKIEBOT_ID }}
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID }}
  NEXT_PUBLIC_HOTJAR_ID: ${{ secrets.NEXT_PUBLIC_HOTJAR_ID }}
  NEXT_PUBLIC_OG_BASE_URL: ${{ secrets.NEXT_PUBLIC_OG_BASE_URL }}
  NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
  NEXT_PUBLIC_STRAPI_API_URL: ${{ secrets.NEXT_PUBLIC_STRAPI_API_URL }}
  CONTACT_FORM_SEND_EMAIL_DOMAIN: ${{ secrets.CONTACT_FORM_SEND_EMAIL_DOMAIN }}
  CONTACT_FORM_RECEIVE_EMAIL: ${{ secrets.CONTACT_FORM_RECEIVE_EMAIL }}
  RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
  SMTP_HOST: ${{ secrets.SMTP_HOST }}
  SMTP_PORT: ${{ secrets.SMTP_PORT }}
  SMTP_USER: ${{ secrets.SMTP_USER }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🔬 Lint
        run: yarn lint:strict

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🔎 Type check
        run: yarn typecheck

  prettier:
    name: 💅 Prettier
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 💅 Prettier check
        run: yarn format:check

  test:
    name: 🃏 Test
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🃏 Run jest
        run: yarn test:coverage

      - name: 📊 Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  build:
    name: 🏗 Build
    runs-on: ubuntu-latest
    needs: [lint, typecheck, prettier, test]
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🏗 Build
        run: yarn build
