name: Lighthouse
on:
  schedule:
    - cron: '30 12 1,15 * *'

jobs:
  lighthouse:
    name: 🚦 Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - run: yarn lhci:mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - run: yarn lhci:desktop
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
